version: '3.7'

services:

  vault-app:
    container_name: vault-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
      - '35729:35729'
    environment:
      - NODE_ENV=development